name: utilities
description: Utilities
version: 0.0.8
homepage: ''

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  path_provider: ^2.0.5
  universal_io: ^2.0.4
  floor: ^1.2.0
  intl: ^0.17.0
  http: ^0.13.3

dev_dependencies:
  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
