name: utilities
description: Utilities
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.27
  universal_io: ^1.0.2
  floor: ^0.19.1
  intl: ^0.17.0
  http: ^0.13.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  floor_generator: ^0.19.1
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
