name: utilities
description: Utilities
version: 0.0.3
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0-nullsafety.1
  path_provider: ^2.0.0-nullsafety
  universal_io: ^2.0.0
  floor: ^1.0.0
  intl: ^0.17.0
  http: ^0.13.0

dev_dependencies:
  floor_generator: ^1.0.0
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
